// Project Euler: Problem 2 
// Title: Even Fibonacci numbers 
// Prompt: Each new term in the Fibonacci sequence is generated by adding the 
//         previous two terms. By starting with 1 and 2, the first 10 terms will //         be:
//         1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//         By considering the terms in the Fibonacci sequence whose values do not
//         exceed four million, find the sum of the even-valued terms.
// Date of first attempt: 2015-06-10 
// Date completed: -, -th person to complete.

#include <iostream>
#include <vector>

using namespace std;

vector <int> FibonacciSequence;
int UpperLimit;

int main(){

  //cout << "Upper Limit? ";
  //cin >> UpperLimit;

  int FirstFibonacci=0;
  int SecondFibonacci=1;
  int ThirdFibonacci;

  for (int i=0; i<=10; i++){
    ThirdFibonacci=FirstFibonacci+SecondFibonacci;
    FibonacciSequence.push_back(ThirdFibonacci);
    SecondFibonacci=ThirdFibonacci;
    FirstFibonacci=SecondFibonacci;
  }


  cout << "Sum of even Fibonacci sequence, up to " << UpperLimit << " is: " << endl;


  for (int j=0; j<FibonacciSequence.size();j++){
  cout << FibonacciSequence[j] <<" ";
  }

}
